### ISSUE TITLE
type problems

### ISSUE THREAD

**Issue by evancz** [elm-lang/elm-compiler#1373]
This is a meta issue for organizing things more clearly. If you'd like to add to it, open a separate issue.
#### Known Issues
- [x] Problem with `type alias X a = a` - #1371
- [x] Problems with constrained type variables - #1581, #1268, #1270, #1281, #1316
- [ ] No kind checking - #1146, #917, #1505, #1542, #1598, #1645
- [x] Very particular shadowing issue - #952

**Comment by evancz** [comment]
https://github.com/elm-lang/elm-compiler/commit/5fe9bb9602163927295a6b37a64fd47f982d502a fixes the reported problems with constrained type variables.

**Comment by evancz** [comment]
Closing to track "kind checking" specifically.
