### ISSUE TITLE
parser problems

### ISSUE THREAD

**Issue by evancz** [elm-lang/elm-compiler#1374]
This is a meta issue for organizing things more clearly. If you'd like to add to it, open a separate issue.
#### Dots
- [x] Parser accepts `x.Counter` - #1319 
- [x] Parser rejects `Module.point.x` - #520, #1509
- [x] `type A = B.C` parses - #1200
#### Records
- [x] `{ a = 1, }` - #1356
- [x] Duplicate names in record literals - #1323 
- [x] Duplicate names in record update syntax - #1344
#### Docs
- [x] Spaces in doc comments mess things up - #1376
- [ ] Duplicate entries in @docs comments - #1288
#### Miscellaneous
- [x] `\_b_ -> ...` parses as `\_ b_ -> ...` - #1272
- [x] `f 3x` parses as `f 3 x` - #901
- [ ] Problem with negative numbers in patterns - #1261
- [x] Escaped characters do weird things - #1123, #1279, #1263

**Comment by evancz** [comment]
Fixed enough of these that it makes sense to close this one and just follow along with the last two individually. Also, one of those two is not even a parsing problem.
