### ISSUE TITLE
Tracking parser suggestions

### ISSUE THREAD

**Issue by evancz** [elm-lang/elm-compiler#1375]
**Comments on this issue will be deleted. This is meant to organize problems in a coherent way.**

Known issues:

  - [ ] Remove `(,,)` syntax in types - #1236
  - [ ] Disallow whitespace in unit - #1210
  - [ ] Disallow whitespace in `( + )` - #1213
