### ISSUE TITLE
Tracking code gen problems

### ISSUE THREAD

**Issue by evancz** [elm-lang/elm-compiler#1377]
**Comments on this issue will be deleted. This is meant to organize problems in a coherent way.**

Known issues:

  - [ ] Scoping problem with shadowed variables - #1359
  - [ ] Local operators are not local - #1345
  - [ ] Capturing variables with closures in TCO - #1287
