### ISSUE TITLE
Unable to generalize a type variable. It is not unranked.

### ISSUE THREAD

**Issue by evancz** [elm-lang/elm-compiler#1613]
This has been reported by a few folks now. Here are the examples:

- [x] https://github.com/elm-lang/error-message-catalog/issues/185 - very simple one!
- [x] https://github.com/elm-lang/error-message-catalog/issues/184 - pretty simple one
- [x] #1600 - problem with `comparable` in type annotations
- [x] #1609 - problem with `type alias A = {}` and type annotations
- [x] #1582 - problem with `type alias T = Int` and type annotations
- [x] #1638 - problem with `type alias T = Int` and type annotations
- [x] #1569 - type alias + comparable + annotation
- [x] #1657 - number of args does not match type annotation
- [x] #1607 - problem with nested type annotations
- [x] #1633 - problem with `person` vs `Person`
- [x] #1504 - problem with type annotation in `let`
- [x] #1579 - three type annotations clashing
- [x] #1595 - bigger examples in one file
- [x] #1592 - bigger example in many files
- [ ] #1639 - unannotated definition with `a` in sub-annotation

**Comment by evancz** [comment]
Almost everything was fixed by 4b25980d93ada12236c794f35570e197be82f787! Whoo!

There was one that seems to be different, so I reopened that one to track it there.
