### ISSUE TITLE
List of known runtime errors

### ISSUE THREAD

**Issue by TheSeamau5** [elm-lang/elm-compiler#913]
So, if Elm wants to be serious about runtime errors, let's pile all the known ones together so that they can be treated one by one. Some are compiler issues, other are core library issues. Nevertheless, there is value to lumping them all in one big list because a user would care that the core library be as bug-free as the language itself.

- [ ] Using toString in records : https://github.com/elm-lang/elm-compiler/issues/897
- [ ] Weird tuple error : https://github.com/elm-lang/core/issues/201
- [ ] Broken eq on some unicode strings: https://github.com/elm-lang/core/issues/177
- [x] Array repeat given negative value : https://github.com/elm-lang/core/issues/175
- [ ] `toString Json.Encode.null` : https://github.com/elm-lang/core/pull/183
- [ ] `Json.Encode.null == Json.Encode.object []` (and most other cases of comparing null with non-null) elm-lang/core#294
- [ ] Recursively defined values : https://github.com/elm-lang/elm-compiler/issues/873

Please do not hesitate to add more to the list. I'll remove them as their respective issues close.

**Comment by mgold** [comment]
Here's one from #957 (closed in favor of #873):
````elm
x : a
x = x
````
You can make it crash immediately with `y = List.head x` or put it in a signal to crash later:

````elm
bad = Signal.map (\b -> if b then List.head x else Just "foo") Mouse.isDown
````

And of course you can write a recursive function that never terminates, no polymorphic trickery necessary, and you can't detect it in general:

````elm
g : Int -> String
g x = if x < 0 then "done"  else g x
````

**Comment by mgold** [comment]
Array.repeat should be fixed by elm-lang/core#258.

Also, there's function equality: `x = identity == (\y -> y)`

Also, `Signal.mergeMany []` but that will be caught immediately and consensus is to leave it.

**Comment by ThomasWeiser** [comment]
The value `Json.Encode.null` makes some trouble, throwing runtime errors in:

- [ ] `toString Json.Encode.null` elm-lang/core#183
- [ ] `Json.Encode.null == Json.Encode.object []` (and most other cases of comparing null with non-null) elm-lang/core#294

**Comment by evancz** [comment]
It looks like most of the issues are for core. The only compiler ones are #897 and #873 and I don't think we need a meta issue to track those two. One of them already is a meta issue ;)

So do you mind moving this over to `core` and just keeping the core issues?

**Comment by evancz** [comment]
Okay, this needs to be on core. Please move the relevant stuff over to an issue called "meta issue: issues involving potential runtime errors".

**Comment by rtfeldman** [comment]
Done: https://github.com/elm-lang/core/issues/377

**Comment by evancz** [comment]
Thank you!

**Comment by robsimmons** [comment]
For posterity, because I think I've run across this more than once:

The link posted by @rtfeldman is broken, current link is https://github.com/elm/core/issues/377
