### ISSUE TITLE
WIP: improvements to elm-doc

### ISSUE THREAD

**Issue by evancz** [elm-lang/elm-compiler#933]
This is a tracker for fixing the sharp edges of `elm-doc` that can let mistakes slip through.

  * [x] Check for trying to show docs for values that do not exist (#841) or are not exported (#915)
  * [x] Better error message when module docs are missing (#887)
  * [x] Getting confused between type aliases and union types (#881)

**Comment by Apanatshka** [comment]
Can we also get a warning when there is a doc format comment on something but it's not used in the docs? All you need to do silence the warning is remove the `|`. And it will help find things you meant to add to the docs & export, but forgot to.

**Comment by jvoigtlaender** [comment]
Further possible action points, from https://github.com/elm-lang/elm-lang.org/issues/173:
* Check whether all exported values do have a doc comment
* Let `elm-package` or its user guide tell the developer that they should always be running `elm-doc` and checking the command line output (for warnings) before doing an `elm-package publish`

**Comment by evancz** [comment]
All resolved by cb6a361570a9511efbf43340241426648400aea8
